apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-deployment
  namespace: lms
  labels:
    app: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: lms
        image: ghcr.io/lms-community/lyrionmusicserver:9.1.1
        ports:
        - containerPort: 30873
        env:
        - name: HTTP_PORT
          value: "30873"
        - name: EXTRA_ARGS
          value: "--advertiseaddr=192.168.1.74"
        volumeMounts:
        - mountPath: /music
          name: music-volume
          readOnly: true
        - mountPath: /playlist
          name: playlist-volume
          readOnly: false
        - mountPath: /config
          name: config-volume
          readOnly: false
      volumes:
      - name: music-volume
        hostPath:
          path: /home/andrea/music-server/music
          type: Directory
      - name: playlist-volume
        hostPath:
          path: /home/andrea/music-server/playlist
          type: Directory
      - name: config-volume
        hostPath:
          path: /home/andrea/music-server/config
          type: Directory
