apiVersion: v1
kind: Service
metadata:
  labels:
    app: lms
  name: lms-http
  namespace: lms
spec:
  ports:
  - name: http
    nodePort: 30873
    port: 30873
    protocol: TCP
    targetPort: 30873
  selector:
    app: lms
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lms
  name: lms-player
  namespace: lms
spec:
  ports:
  - name: player
    port: 3483
    protocol: UDP
    targetPort: 3483
  selector:
    app: lms
  type: ClusterIP
