- name: Install Docker and Minikube
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: Install Docker using role
      import_role:
        name: docker
    
    - name: Install Minikube using role
      import_role:
        name: minikube
    
    - name: Install tools for devops
      import_role:
        name: tools

    - name: Install Grafana
      import_role:
        name: grafana

    - name: Install Prometheus
      import_role:
        name: prometheus