gitea:
  config:
    database:
      DB_TYPE: postgres
      HOST: postgres-cluster-rw.gitea.svc.cluster.local:5432
      NAME: giteadb
      USER: gitea
      PASSWD: gitea
      SCHEMA: gitea
persistence:
  storageClass: local-path
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP:
  ssh:
    type: ClusterIP
    port: 22
    clusterIP:
valkey-cluster:
  persistence:
    storageClass: local-path