apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: giteadb
  namespace: gitea
spec:
  name: giteadb
  owner: gitea
  cluster:
    name: gitea-pg-cluster
  template: template0
  encoding: UTF8
  localeCollate: en_US.UTF-8
  localeCType: en_US.UTF-8