gitea:
  config:
    database:
      DB_TYPE: postgres
      HOST: postgres-cluster-rw.gitea.svc.cluster.local:5432
      NAME: giteadb
      USER: gitea
      PASSWD: gitea
      SCHEMA: gitea
persistence:
  storageClass: local-path
valkey-cluster:
  persistence:
    storageClass: local-path
postgresql:
  enabled: false
postgresql-ha:
  enabled: false