apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    chart: grafana-community/grafana
    repoURL: ghcr.io/grafana-community/helm-charts/grafana  # note: the oci:// syntax is not included.
    targetRevision: 11.3.2
  destination:
    name: "in-cluster"
    namespace: monitoring