apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana-community.github.io/helm-charts/
    targetRevision: 11.3.2
    helm:
      releaseName: grafana
      values: |
        service:
          type: NodePort
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring