apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    path: .
    chart: prometheus
    repoURL: oci://ghcr.io/prometheus-community/charts/prometheus
    targetRevision: 28.13.0
    helm:
      values: |
        alertmanager:
          persistence:
            storageClass: local-path
        scrapeConfigs:
          node:
            enabled: true
            job_name: ""
            static_configs:
              - targets:
                - localhost:9100
        server:
          persistentVolume:
            storageClass: local-path
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring