---
# tasks file for loki
- name: One way to avoid apt_key once it is removed from your distro, armored keys should use .asc extension, binary should use .gpg
  block:
    - name: Download Grafana GPG key
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /etc/apt/keyrings/grafana.asc
        mode: '0644'

    - name: Add Grafana APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
        filename: grafana
        state: present
        update_cache: true

- name: Install promtail and loki
  apt:
    pkg:
      - promtail
      - loki
    state: latest
    update_cache: true

- name: Start loki with systemd
  ansible.builtin.systemd_service:
    state: restarted
    name: loki
    daemon_reload: true
    enabled: true

- name: Start promtail with systemd
  ansible.builtin.systemd_service:
    state: restarted
    name: promtail
    daemon_reload: true
    enabled: true
